#!/usr/bin/env python3
"""
Auto-ungated brands for Amazon FBA.

These brands have high auto-approval rates for new/newer sellers.
Sourced from Kozan/Leadgeek (281 ASINs), Flips4Miles community lists,
and cross-referenced across multiple FBA seller resources (Feb 2026).

Usage:
    from auto_ungated_brands import is_auto_ungated, AUTO_UNGATED_BRANDS

    if is_auto_ungated("Nike"):
        print("Auto-ungated — safe to source")
"""

# 200+ brands with high auto-ungate success rates (alphabetical)
# These are brands where Amazon typically grants instant approval
# even to newer seller accounts.
AUTO_UNGATED_BRANDS = {
    "Adobe",
    "Adora",
    "Airheads",
    "Aleene's",
    "Alex Toys",
    "Always",
    "American Greetings",
    "Angel Soft",
    "Angelus",
    "Apple",
    "Apple Barrel",
    "Arm & Hammer",
    "Aveeno",
    "Batman",
    "Bauducco",
    "Beckham Hotel Collection",
    "Bentgo",
    "Bethesda",
    "Blue Buffalo",
    "Bounty",
    "Brita",
    "CELSIUS",
    "CRC",
    "Carhartt",
    "Cascade",
    "Catchmaster",
    "Cetaphil",
    "Champion Sports",
    "ChapStick",
    "Charmin",
    "Chefman",
    "Chronicle Books",
    "Chuckit!",
    "Clorox",
    "Cococare",
    "Coleman",
    "Colgate",
    "Columbia",
    "Command",
    "Converse",
    "Core Power",
    "Craft County",
    "Crayola",
    "Crest",
    "Crocs",
    "D'Addario",
    "DASH",
    "DURACELL",
    "Dark Horse Comics",
    "Dawn",
    "Dell",
    "Dickies",
    "Disney",
    "Disney Princess",
    "Dove",
    "Dr. Brown's",
    "Duck",
    "Dunkin'",
    "Earth Mama",
    "Earth Rated",
    "Easy Off",
    "Elegant Baby",
    "Energizer",
    "Ernie Ball",
    "Etch A Sketch",
    "Febreze",
    "Fisher Price",
    "Five Star",
    "Fruit of the Loom",
    "GCI Outdoor",
    "Gatorade",
    "Gerber",
    "Ghirardelli",
    "Gildan",
    "Gillette",
    "Glad",
    "Gloria Vanderbilt",
    "Goldfish",
    "Goo Gone",
    "GoodNites",
    "Grandpa Gus's",
    "Green Mountain Coffee Roasters",
    "Green Sprouts",
    "Greenies",
    "HP",
    "HUGGIES",
    "Hammermill",
    "Hanes",
    "Harry Potter",
    "Hefty",
    "Heinz",
    "Hydro Flask",
    "Jack Link's",
    "JanSport",
    "Jerzees",
    "Johnson's Baby",
    "Just Play",
    "Just for Men",
    "K'Nex",
    "KIND",
    "Kellogg's",
    "Keurig",
    "Kidde",
    "Kleenex",
    "Knorr",
    "Krylon",
    "L'Oreal",
    "Lavazza",
    "Lion Brand Yarn",
    "Lionel",
    "Lipton",
    "Liquid I.V.",
    "Liquitex",
    "Listerine",
    "Loctite",
    "Lodge",
    "Luvs",
    "Lysol",
    "Mary Kay",
    "Mattel Games",
    "McCafe",
    "McFarlane Toys",
    "Melissa & Doug",
    "Micro Machines",
    "Mielle Organics",
    "Mighty Patch",
    "Milk-Bone",
    "Monster Energy",
    "Motrin",
    "Mr. Potato Head",
    "Mrs. Meyers",
    "Mrs. Meyer's",
    "Mueller Austria",
    "Nalgene",
    "Native",
    "Nature Valley",
    "Nature's Bakery",
    "Neutrogena",
    "Nike",
    "Nintendo",
    "Nivea",
    "Offray",
    "Olay",
    "Old Spice",
    "Olympus",
    "Optimum Nutrition",
    "Oral-B",
    "Ortho",
    "Pacon",
    "Pampers",
    "Paula's Choice",
    "Penn",
    "Philips AVENT",
    "Play-Doh",
    "PlayMonster",
    "Pokemon",
    "Pond's",
    "PopSockets",
    "Pull-Ups",
    "Pure Encapsulations",
    "Purell",
    "Purina",
    "Purina ONE",
    "Purina Pro Plan",
    "Radio Flyer",
    "Red Heart",
    "Reynolds",
    "Ring Pop",
    "Rockstar Games",
    "Rubbermaid",
    "Russell Athletic",
    "Rust-Oleum",
    "SAMSUNG",
    "Safari",
    "Samsonite",
    "Scrubbing Bubbles",
    "Sheba",
    "Sony",
    "Sparkling ICE",
    "Spider Man",
    "Spring Valley",
    "Stanley",
    "Starbucks",
    "Swedish Fish",
    "Swiffer",
    "Swimline",
    "Swingline",
    "Terro",
    "Texas Instruments",
    "The Honest Company",
    "The Original Donut Shop",
    "Tomcat",
    "Torani",
    "True Citrus",
    "Twinings",
    "Under Armour",
    "Valvoline",
    "Vandoren",
    "Vital Proteins",
    "Walker's",
    "Weiman",
    "Welch's",
    "Windex",
    "WoodWick",
    "YETI",
    "Zesty Paws",
    "Audible",
    "CollecTons",
    "FREE VILLAGE",
    "GOOTOP",
    "Hunt's",
    "Intuit",
    "KiddieLand",
    "Kids Preferred",
    "LEDVANCE",
    "Littlebits",
    "Loot Crate",
    "MAXTOP",
    "MAXWELL HOUSE",
    "MED PRIDE",
    "Micro Machines",
    "Minties",
    "Moenich Coins & Collectibles",
    "MonoPrice",
    "Music Treasures Co.",
    "New-Ray",
    "New York Puzzle Co.",
    "Nubby Octopus",
    "PLAYTEX",
    "Pup-Peroni",
    "ROUUO",
    "Rescue Runts",
    "SeaKlear",
    "Syngenta",
    "TAURI",
    "TOZO",
    "Tassimo",
    "Tazo",
    "Temptations",
    "Tenmiro",
    "The Legend of Zelda",
    "ThisWorx",
    "Trolls",
    "US Mint",
    "Vortex",
    "adidas",
    "e.l.f.",
    "essence cosmetics",
    "poppi",
    # ── Added 2026-03-16: student-confirmed auto-ungated brands (mined from Discord chats) ──
    "Bath & Body Works",   # oliviamlee confirmed auto-ungated Oct 2024
    "Cuddl Duds",          # alldayfba posted B0BV886Y94 as auto-ungated
    "Danner",              # alldayfba posted B00T6QAD1U as auto-ungated
    "Dryel",               # alldayfba posted B01LXRYMUL as auto-ungated
    "OUT",                 # alldayfba posted B0BZZWBSYD as auto-ungated (OUT store)
    "Plink",               # alldayfba posted B07T9G3CGX as auto-ungated
    # ── Added 2026-02-28: brands falsely flagged as PL by CSV data ──
    "Alani Nu",
    "ALOHA",
    "Atlas",
    "Bai",
    "Bloom Nutrition",
    "BODYARMOR",
    "bubly",
    "C4 Energy",
    "Cellucor",
    "Coca-Cola",
    "DaVinci Gourmet",
    "David",
    "Diet Coke",
    "Dot's Pretzels",
    "Extra",
    "Fanta",
    "FGO",
    "FIJI",
    "Frito-Lay",
    "GHOST",
    "Hint",
    "IQBAR",
    "Kinder's",
    "LaCroix",
    "Lance",
    "Liquid Death",
    "LMNT",
    "Drink LMNT",
    "McCafe",
    "Mead",
    "Monster",
    "Monster Rehab",
    "Nature's Bakery",
    "NERDS",
    "Nespresso",
    "Nestle",
    "Nestle Pure Life",
    "Owala",
    "Peet's Coffee",
    "Pepsi",
    "POWERADE",
    "Premier Protein",
    "Propel",
    "Pure Leaf",
    "Rain-X",
    "Red Bull",
    "Rice Krispies",
    "Spindrift",
    "Sprite",
    "STANLEY",
    "Waterloo",
    "Wonderful",
    "Zevia",
    "Zipfizz",
}

# Lowercase lookup set for case-insensitive matching
_BRANDS_LOWER = {b.lower() for b in AUTO_UNGATED_BRANDS}


def is_auto_ungated(brand_name):
    """Check if a brand is in the auto-ungated list (case-insensitive)."""
    if not brand_name:
        return False
    return brand_name.lower().strip() in _BRANDS_LOWER


def get_ungated_brands_in_category(category_keywords=None):
    """Return auto-ungated brands, optionally filtered by category affinity.

    This is a simple keyword filter — not a definitive category mapping.
    """
    if not category_keywords:
        return sorted(AUTO_UNGATED_BRANDS)

    # Category-brand affinity (rough mapping for common sourcing categories)
    CATEGORY_BRANDS = {
        "grocery": {
            "Airheads", "Bauducco", "CELSIUS", "Core Power", "Dunkin'",
            "Gatorade", "Ghirardelli", "Goldfish", "Green Mountain Coffee Roasters",
            "Heinz", "Jack Link's", "KIND", "Kellogg's", "Keurig", "Knorr",
            "Lavazza", "Lipton", "Liquid I.V.", "McCafe", "Monster Energy",
            "Nature Valley", "Nature's Bakery", "Ring Pop", "Sparkling ICE",
            "Spring Valley", "Starbucks", "Swedish Fish", "The Original Donut Shop",
            "Torani", "True Citrus", "Twinings", "Welch's", "poppi",
        },
        "health": {
            "Always", "Arm & Hammer", "Aveeno", "Cetaphil", "ChapStick",
            "Crest", "Colgate", "Dove", "Gillette", "Johnson's Baby",
            "Just for Men", "L'Oreal", "Listerine", "Mighty Patch",
            "Mielle Organics", "Motrin", "Native", "Neutrogena", "Nivea",
            "Olay", "Old Spice", "Oral-B", "Paula's Choice", "Pond's",
            "Purell", "Vital Proteins",
        },
        "beauty": {
            "Aveeno", "Cetaphil", "Dove", "L'Oreal", "Mary Kay",
            "Mielle Organics", "Native", "Neutrogena", "Nivea", "Olay",
            "Paula's Choice", "Pond's", "e.l.f.", "essence cosmetics",
        },
        "baby": {
            "Dr. Brown's", "Earth Mama", "Elegant Baby", "Fisher Price",
            "GoodNites", "Green Sprouts", "HUGGIES", "Johnson's Baby",
            "Luvs", "Pampers", "Philips AVENT", "Pull-Ups",
            "The Honest Company",
        },
        "toys": {
            "Alex Toys", "Batman", "Crayola", "Disney", "Disney Princess",
            "Etch A Sketch", "Fisher Price", "Harry Potter", "Just Play",
            "K'Nex", "Lionel", "Mattel Games", "McFarlane Toys",
            "Melissa & Doug", "Micro Machines", "Mr. Potato Head",
            "Play-Doh", "PlayMonster", "Pokemon", "Radio Flyer",
            "Spider Man",
        },
        "pets": {
            "Blue Buffalo", "Chuckit!", "Earth Rated", "Greenies",
            "Milk-Bone", "Purina", "Purina ONE", "Purina Pro Plan",
            "Sheba", "Zesty Paws",
        },
        "home": {
            "Angel Soft", "Bounty", "Cascade", "Charmin", "Clorox",
            "Command", "Dawn", "Easy Off", "Febreze", "Glad", "Goo Gone",
            "Hefty", "Kleenex", "Lodge", "Lysol", "Mrs. Meyer's",
            "Reynolds", "Rubbermaid", "Scrubbing Bubbles", "Swiffer",
            "Windex", "WoodWick",
        },
        "apparel": {
            "adidas", "Carhartt", "Columbia", "Converse", "Crocs",
            "Dickies", "Fruit of the Loom", "Gildan", "Gloria Vanderbilt",
            "Hanes", "JanSport", "Jerzees", "Nike", "Russell Athletic",
            "Samsonite", "Under Armour",
        },
        "sports": {
            "Champion Sports", "Coleman", "GCI Outdoor", "Hydro Flask",
            "Nalgene", "Nike", "Optimum Nutrition", "Penn", "Stanley",
            "Swimline", "YETI", "adidas", "Under Armour",
        },
        "electronics": {
            "Adobe", "Dell", "DURACELL", "Energizer", "HP", "Nintendo",
            "Olympus", "PopSockets", "Rockstar Games", "SAMSUNG", "Sony",
            "Texas Instruments",
        },
    }

    keywords_lower = [k.lower() for k in category_keywords] if category_keywords else []
    result = set()
    for kw in keywords_lower:
        if kw in CATEGORY_BRANDS:
            result.update(CATEGORY_BRANDS[kw])

    return sorted(result) if result else sorted(AUTO_UNGATED_BRANDS)


if __name__ == "__main__":
    print(f"Total auto-ungated brands: {len(AUTO_UNGATED_BRANDS)}")
    print(f"\nAll brands (alphabetical):")
    for b in sorted(AUTO_UNGATED_BRANDS):
        print(f"  {b}")
