#!/usr/bin/env python3
"""
Script: competitive_intel_cron.py
Purpose: Weekly competitive intelligence auto-scrape that feeds results
         into the Training Officer for agent improvement proposals.

Usage:
  python execution/competitive_intel_cron.py                  # Run both agency + coaching
  python execution/competitive_intel_cron.py --business agency
  python execution/competitive_intel_cron.py --dry-run        # Show what would run

Schedule: Weekly via launchd or Modal cron (see training_officer_webhook.py)

Flow:
  1. Scrapes competitor ads from Meta Ad Library
  2. Saves raw data to .tmp/competitive-intel/
  3. Generates a summary brief for the Training Officer
  4. Triggers a Training Officer scan to pick up the new intel
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(os.environ.get(
    "NOMAD_NEBULA_ROOT",
    "/Users/Shared/antigravity/projects/nomad-nebula"
))

INTEL_DIR = PROJECT_ROOT / ".tmp" / "competitive-intel"
TRAINING_DIR = PROJECT_ROOT / ".tmp" / "training-officer"
PYTHON = str(PROJECT_ROOT / ".venv" / "bin" / "python3")


def ensure_dirs():
    INTEL_DIR.mkdir(parents=True, exist_ok=True)
    TRAINING_DIR.mkdir(parents=True, exist_ok=True)


def load_env():
    env_file = PROJECT_ROOT / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


def scrape_competitors(business: str, dry_run: bool = False) -> dict:
    """Run the competitor ads scraper for a business vertical."""
    today = datetime.now().strftime("%Y-%m-%d")
    output_file = INTEL_DIR / f"{business}_competitors_{today}.json"

    script = PROJECT_ROOT / "execution" / "scrape_competitor_ads.py"
    cmd = [PYTHON, str(script), "--business", business, "--output", str(output_file)]

    print(f"[competitive-intel] Scraping {business} competitors...")

    if dry_run:
        print(f"[competitive-intel] DRY RUN: Would run: {' '.join(cmd)}")
        return {"business": business, "status": "dry_run", "file": str(output_file)}

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode == 0 and output_file.exists():
            data = json.loads(output_file.read_text())
            print(f"[competitive-intel] Scraped {len(data) if isinstance(data, list) else '?'} ads for {business}")
            return {"business": business, "status": "ok", "file": str(output_file), "count": len(data) if isinstance(data, list) else 0}
        else:
            print(f"[competitive-intel] Scrape failed for {business}: {result.stderr[-200:]}")
            return {"business": business, "status": "error", "error": result.stderr[-200:]}
    except subprocess.TimeoutExpired:
        print(f"[competitive-intel] Scrape timed out for {business}")
        return {"business": business, "status": "timeout"}
    except Exception as e:
        print(f"[competitive-intel] Error: {e}")
        return {"business": business, "status": "error", "error": str(e)}


def generate_intel_brief(results: list) -> Path:
    """Generate a competitive intel brief that the Training Officer will pick up."""
    today = datetime.now().strftime("%Y-%m-%d")
    brief_path = INTEL_DIR / f"intel-brief-{today}.md"

    brief = f"""# Competitive Intelligence Brief — {today}

> Auto-generated by competitive_intel_cron.py
> This file is monitored by the Training Officer for agent improvement signals.

## Scrape Results

"""
    for r in results:
        status = r.get("status", "unknown")
        business = r.get("business", "?")
        count = r.get("count", 0)

        if status == "ok":
            brief += f"- **{business}**: {count} competitor ads scraped → `{r.get('file', '?')}`\n"
        elif status == "error":
            brief += f"- **{business}**: FAILED — {r.get('error', 'unknown error')}\n"
        elif status == "timeout":
            brief += f"- **{business}**: TIMEOUT — scrape took too long\n"
        elif status == "dry_run":
            brief += f"- **{business}**: DRY RUN — would have scraped\n"

    brief += """
## Action Items for Training Officer

1. Analyze new competitor ad angles, hooks, and offers
2. Compare against our current ad copy and outreach messaging
3. Identify gaps or opportunities for differentiation
4. Generate proposals for ads-copy and outreach agents based on findings

## Files to Review

"""
    for r in results:
        if r.get("file"):
            brief += f"- `{r['file']}`\n"

    brief_path.write_text(brief)
    print(f"[competitive-intel] Brief saved to {brief_path}")
    return brief_path


def trigger_training_officer_scan():
    """Trigger a Training Officer scan to pick up the new intel."""
    script = PROJECT_ROOT / "execution" / "training_officer_scan.py"
    print("[competitive-intel] Triggering Training Officer scan...")
    try:
        result = subprocess.run([PYTHON, str(script)], capture_output=True, text=True, timeout=300)
        if result.returncode == 0:
            print("[competitive-intel] Training Officer scan completed.")
        else:
            print(f"[competitive-intel] Scan had issues: {result.stderr[-200:]}")
    except Exception as e:
        print(f"[competitive-intel] Could not trigger scan: {e}")


def main():
    parser = argparse.ArgumentParser(description="Competitive Intel Auto-Scrape → Training Officer")
    parser.add_argument("--business", choices=["agency", "coaching"], help="Scrape specific vertical only")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen")
    parser.add_argument("--no-scan", action="store_true", help="Skip Training Officer scan after scraping")
    args = parser.parse_args()

    load_env()
    ensure_dirs()

    businesses = [args.business] if args.business else ["agency", "coaching"]
    results = []

    for biz in businesses:
        r = scrape_competitors(biz, dry_run=args.dry_run)
        results.append(r)

    # Generate intel brief
    brief_path = generate_intel_brief(results)

    # Trigger scan (unless --no-scan or --dry-run)
    if not args.no_scan and not args.dry_run:
        trigger_training_officer_scan()

    print(f"\n[competitive-intel] Done. Brief: {brief_path}")


if __name__ == "__main__":
    main()
