#!/usr/bin/env python3
"""
regenerate_oc_workspace.py — Rebuild OpenClaw's TOOLS.md and AGENTS.md from live codebase.

Called automatically from watch_inbox.py reindex task and on heartbeat.
Keeps OpenClaw's workspace in sync as the system grows — new scripts, new skills, new bots
are discovered and written into the workspace files automatically.

Usage:
    python3 execution/regenerate_oc_workspace.py           # regenerate all
    python3 execution/regenerate_oc_workspace.py --tools   # only TOOLS.md
    python3 execution/regenerate_oc_workspace.py --agents  # only AGENTS.md
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT  = Path(__file__).parent.parent
OC_WORKSPACE  = Path("/Users/SabboOpenClawAI/.openclaw/workspace/main")
SKILLS_DIR    = PROJECT_ROOT / ".claude" / "skills"
BOTS_DIR      = PROJECT_ROOT / "bots"
EXECUTION_DIR = PROJECT_ROOT / "execution"


# ── Parsers ───────────────────────────────────────────────────────────────────

def parse_skills() -> list[dict]:
    """Extract name, description, trigger from every skill .md file."""
    skills = []
    for f in sorted(SKILLS_DIR.glob("*.md")):
        if f.name.startswith("_"):
            continue
        text = f.read_text(encoding="utf-8")
        name  = _frontmatter(text, "name") or f.stem
        desc  = _frontmatter(text, "description") or ""
        trigger = _frontmatter(text, "trigger") or ""
        skills.append({"name": name, "description": desc, "trigger": trigger})
    return skills


def parse_bots() -> list[dict]:
    """Extract bot name and purpose from identity.md in each bot dir."""
    bots = []
    for bot_dir in sorted(BOTS_DIR.iterdir()):
        if not bot_dir.is_dir() or bot_dir.name.startswith("_"):
            continue
        identity_file = bot_dir / "identity.md"
        if not identity_file.exists():
            continue
        text    = identity_file.read_text(encoding="utf-8")
        # First non-empty, non-frontmatter line as description
        purpose = _first_paragraph(text)
        bots.append({"name": bot_dir.name, "purpose": purpose})
    return bots


def parse_scripts() -> list[dict]:
    """Extract script name and one-line purpose from docstring."""
    scripts = []
    for f in sorted(EXECUTION_DIR.glob("*.py")):
        if f.name.startswith("_"):
            continue
        text   = f.read_text(encoding="utf-8", errors="ignore")
        purpose = _extract_docstring_purpose(text)
        scripts.append({"name": f.name, "purpose": purpose})
    return scripts


# ── Generators ────────────────────────────────────────────────────────────────

def generate_tools_md(skills: list[dict], scripts: list[dict]) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    skill_rows = "\n".join(
        f"| `/{s['name']}` | {s['description'][:80]} |"
        for s in skills
    )

    script_rows = "\n".join(
        f"| `{s['name']}` | {s['purpose'][:80]} |"
        for s in scripts
        if s["purpose"]
    )

    return f"""# Tools & Capabilities
<!-- auto-generated by regenerate_oc_workspace.py — last updated {ts} -->

Everything OpenClaw can delegate to Claude Code. Full JSON formats for common tasks
are in the static section below. This header is auto-regenerated on every reindex.

## How to Delegate to Claude Code

Drop a JSON file in `/Users/Shared/antigravity/inbox/` named `YYYYMMDDHHMMSS-<task_type>.json`.
Claude Code picks it up within 5 seconds. Result in `/Users/Shared/antigravity/outbox/`.

---

## Claude Code Slash Commands ({len(skills)} available)

Invoke any skill via `run_ide_task` with `"instruction": "Run /skill-name [args]"`.

| Skill | Description |
|---|---|
{skill_rows}

---

## All Execution Scripts ({len(scripts)} available)

Reference these in `run_ide_task` instructions when you need a specific script.

| Script | Purpose |
|---|---|
{script_rows}

---

## Core Inbox Task Types (with exact JSON)

### Build Anything (Claude Code IDE Task)
```json
{{
  "task": "run_ide_task",
  "project": "nomad-nebula",
  "prompt": "DETAILED INSTRUCTION — be specific: what to build, inputs, outputs, file paths",
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### Sync Decision to Claude Code Memory
```json
{{
  "task": "sync_memory",
  "entries": [{{
    "type": "decision|learning|preference|event|idea",
    "category": "amazon|general|technical|sales|content",
    "title": "One-line summary",
    "content": "Full context",
    "tags": "comma,separated,tags"
  }}],
  "source": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### Lead Generation
```json
{{
  "task": "run_scraper",
  "query": "dentists",
  "location": "Miami FL",
  "max_results": 30,
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### FBA Product Sourcing
```json
{{
  "task": "source_products",
  "mode": "brand|category|retailer|scan|asin|oos|a2a|finder",
  "query": "Jellycat",
  "max_results": 20,
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### Generate Emails / Ad Scripts / VSL
```json
{{
  "task": "generate_emails|generate_ad_scripts|generate_vsl",
  "offer": "Amazon FBA coaching",
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### Propose File Edit (requires Sabbo review)
```json
{{
  "task": "propose_edit",
  "file": "directives/example-sop.md",
  "change_description": "What changes and why",
  "proposed_content": "FULL NEW CONTENT",
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### Ping / Health Check
```json
{{
  "task": "ping",
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```

### Reindex (scan recent codebase changes)
```json
{{
  "task": "reindex",
  "agent": "openclaw",
  "timestamp": "TIMESTAMP"
}}
```
"""


def generate_agents_md(skills: list[dict], bots: list[dict]) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    skill_rows = "\n".join(
        f"| `/{s['name']}` | {s['description'][:70]} |"
        for s in skills
    )

    bot_rows = "\n".join(
        f"| **{b['name']}** | {b['purpose'][:80]} |"
        for b in bots
        if b['name'] not in ('clients', 'creators')
    )

    return f"""# Agent Roster
<!-- auto-generated by regenerate_oc_workspace.py — last updated {ts} -->

Full map of every agent in the ecosystem.

---

## You (OpenClaw — SabboOpenClawAI)

Always-on operator. Telegram interface. Fast decisions. Delegates builds to Claude Code.
Max 4 concurrent agents + 8 subagents.

**Subagents you can spawn:**
- Research — web search + synthesis
- Content — draft content, outlines, scripts
- Analysis — score/rank options, analyze data
- Comms — draft emails, DMs, messages for review

---

## Claude Code (sabbojb — the builder)

Handles file edits, code, scripts, deep builds. Reach it via inbox JSON.

**Inbox:** `/Users/Shared/antigravity/inbox/`
**Outbox:** `/Users/Shared/antigravity/outbox/`
**Build log:** MEMORY.md (auto-updated on every file change)

### Slash Commands ({len(skills)} skills)

| Skill | Description |
|---|---|
{skill_rows}

---

## Specialized Bots (nomad-nebula/bots/)

Claude Code manages these. You can reference their expertise or ask CC to invoke them.

| Bot | Purpose |
|---|---|
{bot_rows}

---

## Nova (Student-Facing — Discord + 247profits.org/academy/chat)

- Discord: Nova#6845, guild 1185214150222286849
- 37 FAQ entries, 88 YT videos, 271 IG Reels, 2hr training
- Launchd: `com.sabbo.nova-discord-bot` (always-on)
- **NOT you.** Nova handles students. You handle Sabbo.

---

## Sales Manager (247growth.org)

- NEPQ coaching, closer performance, objection tracking
- Separate Claude API integration on the closer dashboard
- **NOT you.** Internal tool for Sabbo's sales team.

---

## Communication Protocol

| Direction | Method |
|---|---|
| You → Claude Code | Drop JSON in inbox/ |
| Claude Code → You | Writes outbox/ + updates MEMORY.md |
| You → CC memory | `sync_memory` task (after every meaningful conversation) |
| CC → Your context | MEMORY.md auto-updated on every file change |
| Shared truth | `/Users/Shared/antigravity/memory/ceo/memory.db` |
"""


# ── Writer ────────────────────────────────────────────────────────────────────

def write_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    path.chmod(0o664)
    print(f"  ✓ {path.name} ({len(content):,} chars, {len(content.splitlines())} lines)")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _frontmatter(text: str, key: str) -> str:
    m = re.search(rf"^{key}:\s*(.+)$", text, re.MULTILINE)
    return m.group(1).strip().strip('"') if m else ""


def _first_paragraph(text: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line and not line.startswith("#") and not line.startswith(">") and not line.startswith("---"):
            return line[:100]
    return ""


def _extract_docstring_purpose(text: str) -> str:
    """Get the Purpose line from a script's module docstring only.

    MED-5: Previous version searched the full file, causing regex source code
    inside the file body to leak into the generated TOOLS.md descriptions.
    Now restricted to the first 1500 chars and searches within the extracted
    docstring content only — never the surrounding source code.
    """
    header = text[:1500]
    # Extract module-level docstring content
    m = re.search(r'"""(.*?)"""', header, re.DOTALL)
    if not m:
        m = re.search(r"'''(.*?)'''", header, re.DOTALL)
    if not m:
        return ""
    docstring = m.group(1)
    # Look for Purpose: label within docstring text
    pm = re.search(r'Purpose:\s*(.+)', docstring)
    if pm:
        result = pm.group(1).strip()
        if result:
            return result
    # Fall back to first non-empty line of docstring
    for line in docstring.splitlines():
        line = line.strip()
        if line:
            return line[:100]
    return ""


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    args      = sys.argv[1:]
    do_tools  = "--tools" in args or not args
    do_agents = "--agents" in args or not args

    print(f"Regenerating OpenClaw workspace files...")

    skills  = parse_skills()
    bots    = parse_bots()
    scripts = parse_scripts() if do_tools else []

    print(f"  Found: {len(skills)} skills, {len(bots)} bots, {len(scripts)} scripts")

    if do_tools:
        content = generate_tools_md(skills, scripts)
        write_file(OC_WORKSPACE / "TOOLS.md", content)

    if do_agents:
        content = generate_agents_md(skills, bots)
        write_file(OC_WORKSPACE / "AGENTS.md", content)

    print("Done.")


if __name__ == "__main__":
    main()
